"""create members table

Revision ID: 754d691b5318
Revises: 2f48cbb0f0e5
Create Date: 2026-04-14 16:45:21.903850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754d691b5318'
down_revision: Union[str, Sequence[str], None] = '2f48cbb0f0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('role', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("deleted_at IS NULL OR status = 'WITHDRAWN'", name='chk_members_deleted_at_status'),
    sa.CheckConstraint("provider IN ('KAKAO', 'GOOGLE')", name='chk_members_provider'),
    sa.CheckConstraint("role IN ('USER', 'ADMIN')", name='chk_members_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'WITHDRAWN')", name='chk_members_status'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_members_provider_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
