"""create_user_posture_profiles

Revision ID: 80c40137d392
Revises: c3a1d9e4f2b7
Create Date: 2026-04-20 10:14:27.390717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80c40137d392'
down_revision: Union[str, Sequence[str], None] = 'c3a1d9e4f2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_posture_profiles',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), server_default='기본 자세', nullable=False),
    sa.Column('monitor_label', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('uq_one_primary_per_user', 'user_posture_profiles', ['member_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_primary_per_user', table_name='user_posture_profiles', postgresql_where=sa.text('is_primary = TRUE'))
    op.drop_table('user_posture_profiles')
    # ### end Alembic commands ###
