"""create_webcam_alert_type_and_webcam_sessions_tables

Revision ID: ff4b55a3600f
Revises: a0fb508766d8
Create Date: 2026-04-20 14:50:30.925001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff4b55a3600f'
down_revision: Union[str, Sequence[str], None] = 'a0fb508766d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webcam_alert_type',
    sa.Column('alert_type_id', sa.String(length=50), nullable=False),
    sa.Column('alert_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('alert_type_id')
    )
    op.create_table('webcam_sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('good_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bad_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cause_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_posture_profiles.profile_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_webcam_sessions_member_id'), 'webcam_sessions', ['member_id'], unique=False)

    op.bulk_insert(
        sa.table(
            'webcam_alert_type',
            sa.column('alert_type_id', sa.String),
            sa.column('alert_name', sa.String),
            sa.column('description', sa.Text),
        ),
        [
            {'alert_type_id': 'NECK_FORWARD',    'alert_name': '거북목',       'description': '코(머리) 위치가 기준보다 앞으로 이탈'},
            {'alert_type_id': 'HEAD_TILT',       'alert_name': '머리 기울어짐', 'description': '귀 위치 기준 머리가 좌우로 기울어짐'},
            {'alert_type_id': 'SHOULDER_SLOPE',  'alert_name': '어깨 기울기',   'description': '좌우 어깨 높이 또는 위치 이탈'},
            {'alert_type_id': 'HIP_DEVIATION',   'alert_name': '골반 틀어짐',   'description': '좌우 골반 위치 이탈'},
            {'alert_type_id': 'BAD_POSTURE',     'alert_name': '나쁜 자세',     'description': '종합 자세 이탈 판정'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webcam_sessions_member_id'), table_name='webcam_sessions')
    op.drop_table('webcam_sessions')
    op.drop_table('webcam_alert_type')
    # ### end Alembic commands ###
